entramados = [
    {
        title: "blusa-chiapas1",
        price: 800,
        id: 0,
        photo: "./assets/img/products/blusa-chiapas1.jpg",
        state:"CHIAPAS", 
    },
    {
        title: "bolsa-cdmx",
        price: 300,
        id: 1,
        photo: "./assets/img/products/bolsa-cdmx.png",
        state:"CDMX", 
    },
    {
        title: "camisa-tenango1",
        price: 600,
        id: 2,
        photo: "./assets/img/products/camisa-tenango1.jpg",
        state:"HIDALGO", 
    },
    {
        title: "cartera-cdmx",
        price: 400,
        id: 3,
        photo: "./assets/img/products/cartera-cdmx.jpeg",
        state:"CDMX", 
    },
    {
        title: "cartera-cdmx1",
        price: 400,
        id: 4,
        photo: "./assets/img/products/cartera-cdmx1.jpeg",
        state:"CDMX", 
    },
    {
        title: "cojin-cdmx",
        price: 400,
        id: 5,
        photo: "./assets/img/products/cojin-cdmx.png",
        state:"CDMX", 
    },
    {
        title: "cojin-tenango",
        price: 400,
        id: 6,
        photo: "./assets/img/products/cojin-tenango1.jpg",
        state:"HIDALGO", 
    },
    {
        title: "estuche-cdmx1",
        price: 400,
        id: 7,
        photo: "./assets/img/products/estuche-cdmx1.png",
        state:"CDMX", 
    },
    {
        title: "estuche-cdmx5",
        price: 400,
        id: 8,
        photo: "./assets/img/products/estuche-cdmx5.png",
        state:"CDMX", 
    },
    {
        title: "estuche-cdmx7",
        price: 400,
        id: 9,
        photo: "./assets/img/products/estuche-cdmx7.png",
        state:"CDMX", 
    },
    {
        title: "funda-cdmx",
        price: 400,
        id: 10,
        photo: "./assets/img/products/funda-cdmx.png",
        state:"CDMX", 
    },
    {
        title: "funda-cdmx1",
        price: 400,
        id: 11,
        photo: "./assets/img/products/funda-cdmx1.png",
        state:"CDMX", 
    },
    {
        title: "rebozo-cdmx",
        price: 700,
        id: 12,
        photo: "./assets/img/products/rebozo-cdmx.png",
        state:"CDMX", 
    },
    {
        title: "rebozo-cdmx1",
        price: 700,
        id: 13,
        photo: "./assets/img/products/rebozo-cdmx1.jpg",
        state:"CDMX", 
    },
    {
        title: "sarape-cdmx",
        price: 900,
        id: 14,
        photo: "./assets/img/products/sarape-cdmx.png",
        state:"CDMX", 
    },
]